server:
  port: 8080
spring:
  application:
    name: hxyServer
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/hxy?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 333

  thymeleaf:
    cache: false